title: dygest
description: Document Insights Generator
# Local Setting
# baseurl: ""
# url: ""
# Remote Setting
baseurl: ""
url: "https://tsmdt.github.io/dygest"
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: nil
search_enabled: true
nav_enabled: true
aux_links:
  "View on GitHub":
    - "//github.com/tsmdt/dygest"