title: dygest
description: Document Insights Generator
# Local Setting
# baseurl: ""
# url: ""
# Remote Setting
baseurl: "/dygest"
url: "https://tsmdt.github.io"
theme: just-the-docs
search_enabled: true
nav_enabled: true
aux_links:
  "View on GitHub":
    - "//github.com/tsmdt/dygest"